defmodule ChaosPlaygroundWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :chaos_playground

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_chaos_playground_key",
    signing_salt: "rIg04Ir+",
    same_site: "Lax"
  ]

  # :x_headers (X-Forwarded-For crudo) además de :peer_data — el socket WS no pasa por
  # el pipeline de plugs de abajo (el RemoteIp de ahí nunca corre para el upgrade de
  # WebSocket), así que quien necesite la IP real del cliente en una LiveView (ver
  # UserLive.Registration.peer_ip/1) tiene que resolverla a mano con
  # RemoteIp.from(x_headers) en vez de confiar en peer_data (que es el peer TCP crudo,
  # es decir el proxy, no el cliente).
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, :x_headers, session: @session_options]],
    longpoll: [connect_info: [:peer_data, :x_headers, session: @session_options]]

  # Reescribe conn.remote_ip a partir de X-Forwarded-For/Forwarded cuando el request
  # llega de un salto conocido (loopback/redes privadas — el default de RemoteIp cuando
  # no se configuran :proxies explícitos, que es exactamente la topología de este deploy:
  # un solo host Dokku con nginx como reverse proxy delante de la app). Sin esto,
  # conn.remote_ip es siempre la IP del proxy — el mismo valor para todos los clientes —
  # y los rate limiters por IP (RateLimitAuth) terminan compartiendo un balde único.
  # Tiene que ir temprano en el pipeline, antes del Router (que es donde se lee
  # conn.remote_ip más abajo, en el pipeline :rate_limit_auth).
  plug RemoteIp

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :chaos_playground,
    gzip: not code_reloading?,
    only: ChaosPlaygroundWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :chaos_playground
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ChaosPlaygroundWeb.Router
end
